server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/krish/spring-cloud-config-store
#          tells that search into folder matching this pattern
#          http://localhost/serice/sufix
#          we can add multiple repo
#          search-paths:
#            - '*service'
          uri: https://github.com/krish/microservices-course-on-youtube-config-store
          search-paths:
            - 'service-config/*service'
